use_frameworks!

target 'Asynchronous_Example' do
  pod 'Asynchronous', :path => '../'
  pod 'Asynchronous/Alamofire', :path => '../'
  pod 'Asynchronous/BrightFutures', :path => '../'
  pod 'Asynchronous/HydraAsync', :path => '../'
  pod 'Asynchronous/PromiseKit', :path => '../'
  pod 'Asynchronous/Promises', :path => '../'
  pod 'Asynchronous/Then', :path => '../'

  target 'Asynchronous_Tests' do
    inherit! :search_paths
    pod 'Asynchronous', :path => '../'
    pod 'Asynchronous/BrightFutures', :path => '../'
    pod 'Asynchronous/HydraAsync', :path => '../'
    pod 'Asynchronous/PromiseKit', :path => '../'    
  end
end
