osx_image: xcode9
language: objective-c
cache: cocoapods
env:
  global:
  - CODECOV_TOKEN: 0357b740-0155-4cbe-b5c0-a758fb8d94d0
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Asynchronous.xcworkspace -scheme Async-Example -sdk iphonesimulator11.0 -destination 'OS=11.0,name=iPhone 8 Plus' ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)